### PR TITLE
Port to NET Core/Standard

### LINKED ISSUE #5: NET Core or NET Standard version?
I've got errors `Could not load file or assembly 'System.Device, Version=4.0.0.0` while running my NET Core app.

### PR DESCRIPTION
**Pull request by KvanTTT**
Add GeoCoordinate.NetStandard1 dependency for working with GeoCoordinate; fixes #5

### CODE REVIEW

**Comment by xjose97x** [comment]
Great job @KvanTTT

**Comment by KvanTTT** [comment]
Any chance to upload a new nuget version?

**Comment by xjose97x** [comment]
@KvanTTT yes will do that early this week

**Comment by KvanTTT** [comment]
Any updates?)

**Comment by danbopes** [comment]
@xjose97x This STILL hasn't been uploaded to nuget more than a year later. This is a big blocker for my project (I'm likely going to have to download from master in the meantime).

**Comment by KvanTTT** [comment]
Take a look at https://github.com/Genbox/WolframAlpha It has .NET Standard 2.0 nuget version. Moreover, it does not have dependencies.

**Pull request merged**
